[project]
name = "deep-learning-from-scratch-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dezero>=0.0.13",
    "gymnasium[classic-control]>=1.2.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
]
